# Generated by Django 3.0.3 on 2020-07-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='check_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('check_date', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='upload_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
                ('md5', models.CharField(default='', max_length=33)),
                ('size', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
